services:
  - type: web
    name: affiliate-html-maker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Affiliate HTML Maker
      - key: AFFILIATE_TAG
        value: costco-item-22
      - key: OCR_SPACE_API_KEY
        value: helloworld
